-- D1: partition iot_room_state_decoded by RANGE (mesure_at) monthly
-- UNIQUE(raw_id) → UNIQUE(raw_id, mesure_at). Edge must upsert onConflict raw_id,mesure_at.
-- Keeps iot_room_state_decoded_legacy for rollback (DROP later after soak).
-- Applied on iot-cloud after explicit approval 2026-08-05.

CREATE TABLE public.iot_room_state_decoded_p (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  raw_id bigint NOT NULL,
  lsind_regist_no text NOT NULL DEFAULT '',
  item_code text NOT NULL DEFAULT '',
  module_uid smallint NOT NULL,
  topic text,
  wire_ver smallint NOT NULL,
  packet_mode text NOT NULL DEFAULT 'live',
  history boolean NOT NULL DEFAULT false,
  controller_key text NOT NULL,
  eqpmn_no text NOT NULL DEFAULT '',
  stall_ty_code text NOT NULL DEFAULT '',
  stall_no text NOT NULL DEFAULT '',
  mesure_dt text NOT NULL,
  mesure_at timestamptz NOT NULL,
  run_mode smallint,
  temp_c numeric,
  humidity_pct numeric,
  decoded_json jsonb NOT NULL,
  decode_status text NOT NULL DEFAULT 'ok',
  decode_error text,
  decode_source text NOT NULL DEFAULT 'edge',
  received_at timestamptz NOT NULL,
  decoded_at timestamptz NOT NULL DEFAULT now(),
  fan_supply_pct numeric,
  fan_exhaust_pct numeric,
  fan_intake_pct numeric,
  CONSTRAINT iot_room_state_decoded_p_pkey PRIMARY KEY (id, mesure_at),
  CONSTRAINT uq_iot_decoded_p_raw_id_mesure UNIQUE (raw_id, mesure_at),
  CONSTRAINT iot_room_state_decoded_p_packet_mode_check
    CHECK (packet_mode = ANY (ARRAY['live'::text, 'history'::text, 'replay'::text])),
  CONSTRAINT iot_room_state_decoded_p_decode_status_check
    CHECK (decode_status = ANY (ARRAY['ok'::text, 'skipped'::text, 'failed'::text])),
  CONSTRAINT iot_room_state_decoded_p_decode_source_check
    CHECK (decode_source = ANY (ARRAY['edge'::text, 'backfill'::text, 'manual'::text])),
  CONSTRAINT iot_room_state_decoded_p_raw_id_fkey
    FOREIGN KEY (raw_id) REFERENCES public.iot_room_state_raw(id) ON DELETE CASCADE
) PARTITION BY RANGE (mesure_at);

CREATE TABLE public.iot_room_state_decoded_p_2026_07
  PARTITION OF public.iot_room_state_decoded_p
  FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE TABLE public.iot_room_state_decoded_p_2026_08
  PARTITION OF public.iot_room_state_decoded_p
  FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE TABLE public.iot_room_state_decoded_p_2026_09
  PARTITION OF public.iot_room_state_decoded_p
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

CREATE TABLE public.iot_room_state_decoded_p_2026_10
  PARTITION OF public.iot_room_state_decoded_p
  FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');

CREATE TABLE public.iot_room_state_decoded_p_default
  PARTITION OF public.iot_room_state_decoded_p DEFAULT;

CREATE INDEX idx_iot_decoded_p_farm_received
  ON public.iot_room_state_decoded_p (lsind_regist_no, item_code, module_uid, received_at DESC);

CREATE INDEX idx_iot_decoded_p_live_latest
  ON public.iot_room_state_decoded_p (lsind_regist_no, item_code, module_uid, controller_key, received_at DESC)
  WHERE packet_mode = 'live' AND decode_status = 'ok';

CREATE INDEX idx_iot_decoded_p_mesure_at
  ON public.iot_room_state_decoded_p (lsind_regist_no, item_code, module_uid, mesure_at DESC);

INSERT INTO public.iot_room_state_decoded_p (
  id, raw_id, lsind_regist_no, item_code, module_uid, topic, wire_ver, packet_mode,
  history, controller_key, eqpmn_no, stall_ty_code, stall_no, mesure_dt, mesure_at,
  run_mode, temp_c, humidity_pct, decoded_json, decode_status, decode_error,
  decode_source, received_at, decoded_at, fan_supply_pct, fan_exhaust_pct, fan_intake_pct
)
SELECT
  id, raw_id, lsind_regist_no, item_code, module_uid, topic, wire_ver, packet_mode,
  history, controller_key, eqpmn_no, stall_ty_code, stall_no, mesure_dt, mesure_at,
  run_mode, temp_c, humidity_pct, decoded_json, decode_status, decode_error,
  decode_source, received_at, decoded_at, fan_supply_pct, fan_exhaust_pct, fan_intake_pct
FROM public.iot_room_state_decoded;

SELECT setval(
  pg_get_serial_sequence('public.iot_room_state_decoded_p', 'id'),
  GREATEST(
    (SELECT COALESCE(MAX(id), 1) FROM public.iot_room_state_decoded_p),
    1
  ),
  true
);

CREATE TRIGGER trg_iot_decoded_fill_keys
  BEFORE INSERT OR UPDATE ON public.iot_room_state_decoded_p
  FOR EACH ROW
  EXECUTE FUNCTION public.iot_decoded_fill_keys();

-- mesure_at: Edge sends partition key; do not attach sync_decoded_mesure_at
-- (partition clones caused "moving row" on upsert). See 20260805162000.

ALTER TABLE public.iot_room_state_decoded_p ENABLE ROW LEVEL SECURITY;

CREATE POLICY decoded_select_scoped ON public.iot_room_state_decoded_p
  FOR SELECT TO authenticated
  USING (user_can_read_farm(auth.uid(), lsind_regist_no, item_code));

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
  ON public.iot_room_state_decoded_p TO anon, authenticated, service_role;

-- Swap under lock; catch rows written during copy
LOCK TABLE public.iot_room_state_decoded IN ACCESS EXCLUSIVE MODE;

INSERT INTO public.iot_room_state_decoded_p (
  id, raw_id, lsind_regist_no, item_code, module_uid, topic, wire_ver, packet_mode,
  history, controller_key, eqpmn_no, stall_ty_code, stall_no, mesure_dt, mesure_at,
  run_mode, temp_c, humidity_pct, decoded_json, decode_status, decode_error,
  decode_source, received_at, decoded_at, fan_supply_pct, fan_exhaust_pct, fan_intake_pct
)
SELECT
  d.id, d.raw_id, d.lsind_regist_no, d.item_code, d.module_uid, d.topic, d.wire_ver, d.packet_mode,
  d.history, d.controller_key, d.eqpmn_no, d.stall_ty_code, d.stall_no, d.mesure_dt, d.mesure_at,
  d.run_mode, d.temp_c, d.humidity_pct, d.decoded_json, d.decode_status, d.decode_error,
  d.decode_source, d.received_at, d.decoded_at, d.fan_supply_pct, d.fan_exhaust_pct, d.fan_intake_pct
FROM public.iot_room_state_decoded d
WHERE NOT EXISTS (
  SELECT 1
  FROM public.iot_room_state_decoded_p p
  WHERE p.raw_id = d.raw_id AND p.mesure_at = d.mesure_at
);

ALTER TABLE public.iot_room_state_decoded RENAME TO iot_room_state_decoded_legacy;

-- Legacy indexes keep old names and collide if we rename new indexes to them
ALTER INDEX public.iot_room_state_decoded_pkey RENAME TO iot_room_state_decoded_legacy_pkey;
ALTER INDEX public.uq_iot_decoded_raw_id RENAME TO uq_iot_decoded_legacy_raw_id;
ALTER INDEX public.idx_iot_decoded_farm_received RENAME TO idx_iot_decoded_legacy_farm_received;
ALTER INDEX public.idx_iot_decoded_live_latest RENAME TO idx_iot_decoded_legacy_live_latest;
ALTER INDEX public.idx_iot_decoded_mesure_at RENAME TO idx_iot_decoded_legacy_mesure_at;
ALTER SEQUENCE public.iot_room_state_decoded_id_seq RENAME TO iot_room_state_decoded_legacy_id_seq;

ALTER TABLE public.iot_room_state_decoded_p RENAME TO iot_room_state_decoded;
ALTER SEQUENCE public.iot_room_state_decoded_p_id_seq RENAME TO iot_room_state_decoded_id_seq;

ALTER INDEX public.iot_room_state_decoded_p_pkey RENAME TO iot_room_state_decoded_pkey;
ALTER INDEX public.uq_iot_decoded_p_raw_id_mesure RENAME TO uq_iot_decoded_raw_id_mesure;
ALTER INDEX public.idx_iot_decoded_p_farm_received RENAME TO idx_iot_decoded_farm_received;
ALTER INDEX public.idx_iot_decoded_p_live_latest RENAME TO idx_iot_decoded_live_latest;
ALTER INDEX public.idx_iot_decoded_p_mesure_at RENAME TO idx_iot_decoded_mesure_at;

ALTER TABLE public.iot_room_state_decoded
  RENAME CONSTRAINT iot_room_state_decoded_p_packet_mode_check
  TO iot_room_state_decoded_packet_mode_check;
ALTER TABLE public.iot_room_state_decoded
  RENAME CONSTRAINT iot_room_state_decoded_p_decode_status_check
  TO iot_room_state_decoded_decode_status_check;
ALTER TABLE public.iot_room_state_decoded
  RENAME CONSTRAINT iot_room_state_decoded_p_decode_source_check
  TO iot_room_state_decoded_decode_source_check;
ALTER TABLE public.iot_room_state_decoded
  RENAME CONSTRAINT iot_room_state_decoded_p_raw_id_fkey
  TO iot_room_state_decoded_raw_id_fkey;

DROP VIEW IF EXISTS public.v_iot_farm_overview;
DROP VIEW IF EXISTS public.v_iot_dashboard_list;
DROP VIEW IF EXISTS public.v_iot_decoded_latest;

CREATE VIEW public.v_iot_decoded_latest AS
SELECT DISTINCT ON (lsind_regist_no, item_code, module_uid, controller_key)
  id,
  raw_id,
  lsind_regist_no,
  item_code,
  module_uid,
  controller_key,
  eqpmn_no,
  stall_ty_code,
  stall_no,
  wire_ver,
  packet_mode,
  run_mode,
  temp_c,
  humidity_pct,
  mesure_dt,
  mesure_at,
  decoded_json,
  received_at,
  decoded_at
FROM public.iot_room_state_decoded d
WHERE packet_mode = 'live'
  AND decode_status = 'ok'
  AND wire_ver = 12
ORDER BY lsind_regist_no, item_code, module_uid, controller_key, received_at DESC;

CREATE VIEW public.v_iot_dashboard_list AS
SELECT DISTINCT ON (lsind_regist_no, item_code, module_uid, controller_key)
  id,
  raw_id,
  lsind_regist_no,
  item_code,
  module_uid,
  controller_key,
  eqpmn_no,
  stall_ty_code,
  stall_no,
  wire_ver,
  packet_mode,
  run_mode,
  temp_c,
  humidity_pct,
  fan_supply_pct,
  fan_exhaust_pct,
  fan_intake_pct,
  mesure_dt,
  mesure_at,
  received_at,
  decoded_at,
  NULLIF(extract_channel_a_thermo(decoded_json -> 'channels') ->> 'setpointTemp', '')::numeric AS setpoint_temp,
  NULLIF(extract_channel_a_thermo(decoded_json -> 'channels') ->> 'tempDeviation', '')::numeric AS temp_deviation,
  (extract_channel_a_thermo(decoded_json -> 'channels') ->> 'minVentPct')::numeric AS min_vent_pct,
  (extract_channel_a_thermo(decoded_json -> 'channels') ->> 'maxVentPct')::numeric AS max_vent_pct
FROM public.iot_room_state_decoded d
WHERE packet_mode = 'live'
  AND decode_status = 'ok'
  AND wire_ver = 12
ORDER BY lsind_regist_no, item_code, module_uid, controller_key, received_at DESC;

GRANT SELECT ON public.v_iot_decoded_latest TO anon, authenticated, service_role;
GRANT SELECT ON public.v_iot_dashboard_list TO anon, authenticated, service_role;

CREATE VIEW public.v_iot_farm_overview AS
SELECT lsind_regist_no,
  item_code,
  count(*)::integer AS controller_count,
  count(*) FILTER (WHERE received_at < (now() - '01:00:00'::interval))::integer AS offline_count,
  avg(temp_c) FILTER (WHERE temp_c IS NOT NULL) AS avg_temp_c,
  avg(humidity_pct) FILTER (WHERE humidity_pct IS NOT NULL) AS avg_humidity_pct,
  max(received_at) AS latest_received_at
FROM v_iot_dashboard_list l
GROUP BY lsind_regist_no, item_code;

GRANT SELECT ON public.v_iot_farm_overview TO anon, authenticated, service_role;

-- public.iot_room_state_decoded_archive stub removed in 20260805171000
-- (retention uses schema archive via cleanup_iot_retention_30d)

COMMENT ON TABLE public.iot_room_state_decoded IS
  'D1 partitioned by mesure_at (monthly). UNIQUE(raw_id, mesure_at).';

