# Remote project: iot-cloud (ompufmezugftzoergdbn)
project_id = "ompufmezugftzoergdbn"

[db]
port = 54322
major_version = 15

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.decode-batch]
verify_jwt = false

[functions.fetch-weather-warn]
verify_jwt = false

[studio]
enabled = true
